=== Kashdog/Blockly/demos/DataClassification&Rules/DataRuleFunctionsLibrary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.ibm.com/infosphere/dataquality/datarulefunctionslibrary" xmlns="http://www.ibm.com/infosphere/dataquality/datarulefunctionslibrary" xmlns:xsd="http://www.w3.org/2001/XMLSchema">


   	<xsd:simpleType name="datatype">
   		<xsd:restriction base="xsd:string">
   			<xsd:enumeration value="numeric" />
   			<xsd:enumeration value="double" />
   			<xsd:enumeration value="int" />
   			<xsd:enumeration value="float" />
   			<xsd:enumeration value="string" />
   			<xsd:enumeration value="date" />
   			<xsd:enumeration value="time" />
   			<xsd:enumeration value="timestamp" />
   			<xsd:enumeration value="list" />
   			<xsd:enumeration value="any" />
   			<xsd:enumeration value="unknown"></xsd:enumeration>
   		</xsd:restriction>
   	</xsd:simpleType>

   	<xsd:simpleType name="executiontype">
   		<xsd:restriction base="xsd:string">
   			<xsd:enumeration value="normal" />
   			<xsd:enumeration value="precomputedAggregation" />
   			<xsd:enumeration value="computedFromMultipleAggregations"></xsd:enumeration>
   		</xsd:restriction>
   	</xsd:simpleType>

   	<xsd:simpleType name="operandConstraintType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="isOptional" />
			<xsd:enumeration value="mustBeEmpty" />
			<xsd:enumeration value="mustBeColumn" />
			<xsd:enumeration value="isReferenceColumn" />
			<xsd:enumeration value="mustMatchRegex" />
			<xsd:enumeration value="minValue" />
			<xsd:enumeration value="sameDataTypeAsOtherOperand" />
		</xsd:restriction>
	</xsd:simpleType>

   	<xsd:complexType name="Parameter">
   		<xsd:sequence>
   			<xsd:element name="description" type="xsd:string"
   				minOccurs="0" maxOccurs="1">
   			</xsd:element>
   		</xsd:sequence>
   		<xsd:attribute name="type" type="datatype" use="required" />
   		<xsd:attribute name="name" type="xsd:string" use="optional" />
   		<xsd:attribute name="column" type="xsd:boolean"
   			use="optional" default="false" />
   		<xsd:attribute name="refcolumn" type="xsd:boolean"
   			use="optional" default="false" />
   		<xsd:attribute name="optional" type="xsd:boolean"
   			use="optional" default="false" />
   	</xsd:complexType>

   	<xsd:complexType name="Category">
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1">
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required" />
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Categories">
		<xsd:sequence>
			<xsd:element name="Category" type="Category" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="DataRuleFunctions">
		<xsd:sequence>
			<xsd:element name="DataRuleFunction" type="DataRuleFunction" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="DataRuleFunction">
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" maxOccurs="1">
			</xsd:element>
			<xsd:element name="Parameter" type="Parameter" minOccurs="0"
				maxOccurs="unbounded">
			</xsd:element>
			<xsd:element name="RequiredAggregation"
				type="RequiredAggregation" minOccurs="0" maxOccurs="unbounded">
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="returnType" type="datatype" use="required" />
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="displayName" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="categoryID" type="xsd:string"
			use="optional" />
		<xsd:attribute name="className" type="xsd:string"
			use="required">
		</xsd:attribute>
		<xsd:attribute name="executionType" type="executiontype"
			use="optional" default="normal">
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="RequiredAggregation">
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

	<xsd:complexType name="DataRuleTest">
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" maxOccurs="1">
			</xsd:element>
			<xsd:element name="TestOperand" type="TestOperand"
				minOccurs="2" maxOccurs="2">
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="displayName" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="categoryID" type="xsd:string"
			use="optional" />
		<xsd:attribute default="normal" name="executionType"
			type="executiontype" use="optional" />
		<xsd:attribute name="className" type="xsd:string"
			use="required" />
	</xsd:complexType>

	<xsd:complexType name="TestOperand">
    	<xsd:sequence>
    		<xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="TestOperandConstraint" type="TestOperandConstraint" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="type" type="datatype" use="required" />
    </xsd:complexType>

    <xsd:complexType name="TestOperandConstraint">
       	<xsd:attribute name="type" type="operandConstraintType" use="required" />
       	<xsd:attribute name="stringValue" type="xsd:string" use="optional" />
       	<xsd:attribute name="numericValue" type="xsd:double" use="optional" />
    </xsd:complexType>

    <xsd:complexType name="DataRuleTests">
    	<xsd:sequence>
    		<xsd:element name="DataRuleTest" type="DataRuleTest" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="DataRuleFunctionsLibrary">
    	<xsd:sequence>
    		<xsd:element name="description" type="xsd:string"
    			minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="Categories" type="Categories"
    			minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="DataRuleFunctions"
    			type="DataRuleFunctions" minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="DataRuleTests" type="DataRuleTests"
    			minOccurs="0" maxOccurs="1">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="optional" />
    	<xsd:attribute name="provider" type="xsd:string"
    		use="optional">
    	</xsd:attribute>
    	<xsd:attribute name="version" type="xsd:string" use="optional"></xsd:attribute>
    </xsd:complexType>

    <xsd:element name="DataRuleFunctionsLibrary" type="DataRuleFunctionsLibrary"></xsd:element>
</xsd:schema>

=== Kashdog/Blockly/demos/IBM-demos/DataRuleFunctionsLibrary.xml
<?xml version="1.0" encoding="UTF-8"?>
    <p:DataRuleFunctionsLibrary xmlns:p="http://www.ibm.com/infosphere/dataquality/datarulefunctionslibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com/infosphere/dataquality/datarulefunctionslibrary ../xsd/DataRuleFunctionsLibrary.xsd " name="Built in functions library" provider="IBM" version="1.10.0">

        <description>Built in data quality rules functions and tests.</description>

        <!--
		##################################################
		###################	Categories ###################
		##################################################
	-->
        <Categories>
            <Category id="general" name="General">
                <description>Functions for general purposes</description>
            </Category>
            <Category id="date/time" name="%category.datetime.name">
                <description>%category.datetime.desc</description>
            </Category>
            <Category id="math" name="%category.math.name">
                <description>%category.math.desc</description>
            </Category>
            <Category id="string" name="%category.string.name">
                <description>%category.string.desc</description>
            </Category>
        </Categories>

        <!--
		##################################################
		###################	Functions ####################
		##################################################
	-->
        <DataRuleFunctions>
            <DataRuleFunction categoryID="general" className="com.ibm.infosphere.dataquality.ruleengine.functions.Coalesce" displayName="replace missing value for %1 with %2" name="coalesce" returnType="any">
                <description>Replace a missing value with a specific value</description>
                <Parameter name="value" type="any">
                    <description>%function.coalesce.param1.desc</description>
                </Parameter>
                <Parameter name="replacementValue" optional="true" type="any">
                    <description>%function.coalesce.param2.desc</description>
                </Parameter>
            </DataRuleFunction>

            <DataRuleFunction categoryID="general" className="com.ibm.infosphere.dataquality.ruleengine.functions.Count" displayName="Number of distinct values of %1 grouped by %2" executionType="precomputedAggregation" name="count" returnType="numeric">
                <description>Aggregate function, provides a count of the number of distinct values of a given column</description>
                <Parameter column="true" name="column" type="any">
                    <description>%function.count.param1.desc</description>
                </Parameter>
                <Parameter column="true" name="groupBy" optional="true" type="any">
                    <description>%function.count.param2.desc</description>
                </Parameter>
            </DataRuleFunction>

            <DataRuleFunction categoryID="general" className="com.ibm.infosphere.dataquality.ruleengine.functions.CountNotNull" displayName="Number of non null values of %1 grouped by %2" executionType="precomputedAggregation" name="count_not_null" returnType="numeric">
                <description>Aggregate function, provides a count of the number of non null values of a given column</description>
                <Parameter column="true" name="column" type="any">
                    <description>%function.count_non_null.param1.desc</description>
                </Parameter>
                <Parameter column="true" name="groupBy" optional="true" type="any">
                    <description>%function.count_non_null.param2.desc</description>
                </Parameter>
            </DataRuleFunction>

            <DataRuleFunction categoryID="general" className="com.ibm.infosphere.dataquality.ruleengine.functions.DataClassesOf" displayName="Data classes matched by %1" name="dataclassesof" returnType="list">
                <description>Returns the list of data classes matched by a value</description>
                <Parameter name="value" type="any">
                    <description>%function.dataclassesof.param1.desc</description>
                </Parameter>
            </DataRuleFunction>

            <DataRuleFunction categoryID="general" className="com.ibm.infosphere.dataquality.ruleengine.functions.Lookup" displayName="lookup %1 from reference key %2 and reference value %3" executionType="precomputedAggregation" name="lookup" returnType="any">
                <description>Replace a value with another value defined in a lookup table</description>
                <Parameter name="value" type="any">
                    <description>%function.lookup.param1.desc</description>
                </Parameter>
                <Parameter name="refkey" refcolumn="true" type="any">
                    <description>%function.lookup.param2.desc</description>
                </Parameter>
                <Parameter name="refvalue" refcolumn="true" type="any">
                    <description>%function.lookup.param3.desc</description>
                </Parameter>
            </DataRuleFunction>

            <DataRuleFunction categoryID="general" className="com.ibm.infosphere.dataquality.ruleengine.functions.Occurrences" displayName="Frequency of %1" executionType="precomputedAggregation" name="occurrences" returnType="numeric">
                <description>Aggregate function, provides the number of occurrences of each value of a given column</description>
                <Parameter column="true" name="column" type="any">
                    <description>%function.occurrences.param1.desc</description>
                </Parameter>--&gt;
                <!-- 			<Parameter type="any" name="groupBy" optional="true" column="true">
				<description>%function.occurrences.param2.desc</description>
			</Parameter>-->
            </DataRuleFunction>
            <DataRuleFunction categoryID="date/time" className="com.ibm.infosphere.dataquality.ruleengine.functions.Date" displayName="current date" name="date" returnType="date">
                <description>Returns the system date from the computer as a date value</description>
            </DataRuleFunction>

            <DataRuleFunction categoryID="date/time" className="com.ibm.infosphere.dataquality.ruleengine.functions.DateValue" displayName="convert %1 to date using format %2" name="datevalue" returnType="date">
                <description>Converts the string representation of a date into a date value</description>
                <Parameter name="string" type="string">
                    <description>%function.datevalue.param1.desc</description>
                </Parameter>
                <Parameter name="format" optional="true" type="string">
                    <description>%function.datevalue.param2.desc</description>
                </Parameter>
            </DataRuleFunction>

            <DataRuleFunction categoryID="date/time" className="com.ibm.infosphere.dataquality.ruleengine.functions.Day" displayName="day of date %1" name="day" returnType="numeric">
                <description>Given a date, returns a number representing the day of the month for that date</description>
                <Parameter name="date" type="date">
                    <description>%function.day.param1.desc</description>
                </Parameter>
            </DataRuleFunction>

            <DataRuleFunction categoryID="date/time" className="com.ibm.infosphere.dataquality.ruleengine.functions.Month" displayName="month of date %1" name="month" returnType="numeric">
                <description>Given a date, returns a number representing the month for that date</description>
                <Parameter name="date" type="date">
                    <description>%function.month.param1.desc</description>
                </Parameter>
            </DataRuleFunction>

            <DataRuleFunction categoryID="date/time" className="com.ibm.infosphere.dataquality.ruleengine.functions.RoundDate" displayName="round date %1 using format %2" name="round_date" returnType="date">
                <description>Returns a rounded value of a date</description>
                <Parameter name="value" type="date">
                    <description>%function.round_date.param1.desc</description>
                </Parameter>
                <Parameter name="format" type="string">
                    <description>%function.round_date.param2.desc</description>
                </Parameter>
            </DataRuleFunction>

            <DataRuleFunction categoryID="date/time" className="com.ibm.infosphere.dataquality.ruleengine.functions.RoundTime" displayName="round time %1 using format %2" name="round_time" returnType="time">
                <description>Returns a rounded value of a time</description>
                <Parameter name="value" type="time">
                    <description>%function.round_time.param1.desc</description>
                </Parameter>
                <Parameter name="format" type="string">
                    <description>%function.round_time.param2.desc</description>
                </Parameter>
            </DataRuleFunction>

            <DataRuleFunction categoryID="date/time" className="com.ibm.infosphere.dataquality.ruleengine.functions.RoundTimeStamp" displayName="round timestamp %1 using format %2" name="round_timestamp" returnType="timestamp">
                <description>Returns a rounded value of a time</description>
                <Parameter name="value" type="timestamp">
                    <description>%function.round_timestamp.param1.desc</description>
                </Parameter>
                <Parameter name="format" type="string">
                    <description>%function.round_timestamp.param2.desc</description>
                </Parameter>
            </DataRuleFunction>
